## CRUD

In [1]:
!pip install numpy

In [5]:
import numpy as np

#### Create

In [7]:
data=np.random.rand(2,3,4)
zeros=np.zeros((2,2,2))
full=np.full((2,2,2),7)
ones=np.ones((2,2,2))

In [17]:
data

array([[[0.37965728, 0.9286767 , 0.00353351, 0.73963193],
        [0.88862196, 0.31950049, 0.80529134, 0.57729117],
        [0.95013409, 0.29709475, 0.55805467, 0.97057278]],

       [[0.75555686, 0.80369452, 0.15169927, 0.71862497],
        [0.29380016, 0.19307756, 0.72055911, 0.83558277],
        [0.79562513, 0.29845804, 0.0536646 , 0.07342223]]])

In [9]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [11]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [15]:
arr=np.array([[1,2,3,4],[1,2,3,4]])

In [16]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

#### Read

In [18]:
# Attributes
shape=data.shape
size=data.size
types=data.dtype

In [19]:
shape

(2, 3, 4)

In [20]:
size

24

In [21]:
types

dtype('float64')

In [22]:
# slicing
arr=data[0]
slicer=data[0:2]
reverse=data[-1]
singleval=data[0][0][0]

In [23]:
arr

array([[0.37965728, 0.9286767 , 0.00353351, 0.73963193],
       [0.88862196, 0.31950049, 0.80529134, 0.57729117],
       [0.95013409, 0.29709475, 0.55805467, 0.97057278]])

In [24]:
slicer

array([[[0.37965728, 0.9286767 , 0.00353351, 0.73963193],
        [0.88862196, 0.31950049, 0.80529134, 0.57729117],
        [0.95013409, 0.29709475, 0.55805467, 0.97057278]],

       [[0.75555686, 0.80369452, 0.15169927, 0.71862497],
        [0.29380016, 0.19307756, 0.72055911, 0.83558277],
        [0.79562513, 0.29845804, 0.0536646 , 0.07342223]]])

In [27]:
reverse
# getting the last array

array([[0.75555686, 0.80369452, 0.15169927, 0.71862497],
       [0.29380016, 0.19307756, 0.72055911, 0.83558277],
       [0.79562513, 0.29845804, 0.0536646 , 0.07342223]])

In [30]:
singleval 
# getting the first data

0.37965727982968367

In [28]:
data

array([[[0.37965728, 0.9286767 , 0.00353351, 0.73963193],
        [0.88862196, 0.31950049, 0.80529134, 0.57729117],
        [0.95013409, 0.29709475, 0.55805467, 0.97057278]],

       [[0.75555686, 0.80369452, 0.15169927, 0.71862497],
        [0.29380016, 0.19307756, 0.72055911, 0.83558277],
        [0.79562513, 0.29845804, 0.0536646 , 0.07342223]]])

#### Update

In [31]:
list1=np.random.rand(10)
list2=np.random.rand(10)

In [32]:
list1
# it has 10 values

array([0.5492561 , 0.61155157, 0.95827289, 0.26900455, 0.21524535,
       0.49038525, 0.769094  , 0.98363562, 0.96309916, 0.47873109])

In [34]:
# Basic math
add=np.add(list1,list2)
sub=np.subtract(list1,list2)
mult=np.multiply(list1,list2)
div=np.divide(list1,list2)
dot=np.dot(list1,list2)

In [35]:
dot

2.538452603566237

### statical functions
*like faaling from sap : SAPLEMM*

In [36]:
sqrt=np.sqrt(34)
ab=np.abs(-7)
power=np.power(3,4)
log=np.log(34)
exp=np.exp([2,3])
mins=np.min(list1)
mazs=np.max(list1)

In [37]:
data[0,0,0]=700
data

array([[[7.00000000e+02, 9.28676703e-01, 3.53350980e-03, 7.39631933e-01],
        [8.88621964e-01, 3.19500487e-01, 8.05291344e-01, 5.77291174e-01],
        [9.50134091e-01, 2.97094754e-01, 5.58054672e-01, 9.70572779e-01]],

       [[7.55556861e-01, 8.03694520e-01, 1.51699270e-01, 7.18624970e-01],
        [2.93800159e-01, 1.93077558e-01, 7.20559110e-01, 8.35582769e-01],
        [7.95625131e-01, 2.98458041e-01, 5.36646034e-02, 7.34222347e-02]]])

In [38]:
# sort data
data.sort()
data

array([[[3.53350980e-03, 7.39631933e-01, 9.28676703e-01, 7.00000000e+02],
        [3.19500487e-01, 5.77291174e-01, 8.05291344e-01, 8.88621964e-01],
        [2.97094754e-01, 5.58054672e-01, 9.50134091e-01, 9.70572779e-01]],

       [[1.51699270e-01, 7.18624970e-01, 7.55556861e-01, 8.03694520e-01],
        [1.93077558e-01, 2.93800159e-01, 7.20559110e-01, 8.35582769e-01],
        [5.36646034e-02, 7.34222347e-02, 2.98458041e-01, 7.95625131e-01]]])

In [39]:
print(data.shape)

(2, 3, 4)


In [40]:
data=data.reshape(2,2,-1)
print(data.shape)

(2, 2, 6)


In [47]:
# append or insert new values
zeros=np.zeros((8))
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
zeros=np.append(zeros,[3,4])
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [49]:
# insert values to a spcific place
zeros=np.insert(zeros,2,5)
print(zeros)

[0. 0. 5. 0. 0. 0. 0. 0. 0. 3. 4.]


#### Delete

In [50]:
data

array([[[3.53350980e-03, 7.39631933e-01, 9.28676703e-01, 7.00000000e+02,
         3.19500487e-01, 5.77291174e-01],
        [8.05291344e-01, 8.88621964e-01, 2.97094754e-01, 5.58054672e-01,
         9.50134091e-01, 9.70572779e-01]],

       [[1.51699270e-01, 7.18624970e-01, 7.55556861e-01, 8.03694520e-01,
         1.93077558e-01, 2.93800159e-01],
        [7.20559110e-01, 8.35582769e-01, 5.36646034e-02, 7.34222347e-02,
         2.98458041e-01, 7.95625131e-01]]])

In [52]:
# delete 1st of all
# it helps to delete specific segments of an array
np.delete(data,0,axis=1)

array([[[0.80529134, 0.88862196, 0.29709475, 0.55805467, 0.95013409,
         0.97057278]],

       [[0.72055911, 0.83558277, 0.0536646 , 0.07342223, 0.29845804,
         0.79562513]]])

In [53]:
# to save an array
np.save("new array",data)

In [54]:
# load the array
load_arr=np.load("new array.npy")

In [55]:
load_arr

array([[[3.53350980e-03, 7.39631933e-01, 9.28676703e-01, 7.00000000e+02,
         3.19500487e-01, 5.77291174e-01],
        [8.05291344e-01, 8.88621964e-01, 2.97094754e-01, 5.58054672e-01,
         9.50134091e-01, 9.70572779e-01]],

       [[1.51699270e-01, 7.18624970e-01, 7.55556861e-01, 8.03694520e-01,
         1.93077558e-01, 2.93800159e-01],
        [7.20559110e-01, 8.35582769e-01, 5.36646034e-02, 7.34222347e-02,
         2.98458041e-01, 7.95625131e-01]]])